#! /usr/bin/python3

import sys, re

obracena_pismena = {
    'a': 'ɐ', 'b': 'q', 'c': 'ɔ', 'd': 'p', 'e': 'ǝ', 'f': 'ɟ', 'g': 'ƃ',
    'h': 'ɥ', 'i': 'ᴉ', 'j': 'ɾ', 'k': 'ʞ', 'l': 'l', 'm': 'ɯ', 'n': 'u',
    'o': 'o', 'p': 'd', 'q': 'b', 'r': 'ɹ', 's': 's', 't': 'ʇ', 'u': 'n',
    'v': 'ʌ', 'w': 'ʍ', 'x': 'x', 'y': 'ʎ', 'z': 'z', 'A': '∀', 'B': 'B',
    'C': 'Ɔ', 'D': 'D', 'E': 'Ǝ', 'F': 'Ⅎ', 'G': 'פ', 'H': 'H', 'I': 'I',
    'J': 'ſ', 'K': 'ʞ', 'L': '˥', 'M': 'W', 'N': 'N', 'O': 'O', 'P': 'Ԁ',
    'Q': 'Q', 'R': 'R', 'S': 'S', 'T': '┴', 'U': '∩', 'V': 'Λ', 'W': 'M',
    'X': 'X', 'Y': '⅄', 'Z': 'Z', '0': '0', '1': 'Ɩ', '2': 'ᄅ', '3': 'Ɛ',
    '4': 'ㄣ', '5': 'ϛ', '6': '9', '7': 'ㄥ', '8': '8', '9': '6', ',': "'",
    '.': '˙', '?': '¿', '!': '¡', '"': '„', "'": ',', '`': ',', '(': ')',
    ')': '(', '[': ']', ']': '[', '{': '}', '}': '{', '<': '>', '>': '<',
    '&': '⅋', '_': '‾',
}

def obrat(text):
    return ''.join(obracena_pismena.get(c, c) for c in reversed(text))

def chyba2(text):
    for c in reversed(text):
        if obracena_pismena.get(c) == None and c != ' ':
            return False
    return True    

def obraceni(vstup, pismeno_je_v_slovniku):
    for line in vstup:
         sys.stdout.write(obrat(line.rstrip())+'\n')
         pismeno_je_v_slovniku = pismeno_je_v_slovniku and chyba2(line.rstrip())
    return pismeno_je_v_slovniku   

napoveda = '''Kratka napoveda
Skript obraci pismena. 
Jine prepinace nez --help zde nejsou
'''

prepinac = re.compile(r"-\S+")
neplatny_prepinac = prepinac.search(' '.join(sys.argv))  

pismeno_je_v_slovniku = True

if len(sys.argv) > 1:
    if '--help' in sys.argv:
        sys.stdout.write(napoveda) 
    elif neplatny_prepinac != None:
        sys.stderr.write(f'Přepínač {neplatny_prepinac.group(0)} neexistuje, viz --help \n')
        exit(1)
    else:
        for vstup in sys.argv[1:]:
            if vstup == '-':
               pismeno_je_v_slovniku = obraceni(sys.stdin, pismeno_je_v_slovniku)
            else:
                with open(vstup, encoding = 'utf-8') as soubor:
                    pismeno_je_v_slovniku = obraceni(soubor, pismeno_je_v_slovniku)
else:
    pismeno_je_v_slovniku = obraceni(sys.stdin, pismeno_je_v_slovniku)

if not pismeno_je_v_slovniku:
    exit(2)
        
